/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1"
	egressservicev1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1/apis/applyconfiguration/egressservice/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EgressServicesGetter has a method to return a EgressServiceInterface.
// A group's client should implement this interface.
type EgressServicesGetter interface {
	EgressServices(namespace string) EgressServiceInterface
}

// EgressServiceInterface has methods to work with EgressService resources.
type EgressServiceInterface interface {
	Create(ctx context.Context, egressService *v1.EgressService, opts metav1.CreateOptions) (*v1.EgressService, error)
	Update(ctx context.Context, egressService *v1.EgressService, opts metav1.UpdateOptions) (*v1.EgressService, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, egressService *v1.EgressService, opts metav1.UpdateOptions) (*v1.EgressService, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EgressService, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EgressServiceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressService, err error)
	Apply(ctx context.Context, egressService *egressservicev1.EgressServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EgressService, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, egressService *egressservicev1.EgressServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EgressService, err error)
	EgressServiceExpansion
}

// egressServices implements EgressServiceInterface
type egressServices struct {
	*gentype.ClientWithListAndApply[*v1.EgressService, *v1.EgressServiceList, *egressservicev1.EgressServiceApplyConfiguration]
}

// newEgressServices returns a EgressServices
func newEgressServices(c *K8sV1Client, namespace string) *egressServices {
	return &egressServices{
		gentype.NewClientWithListAndApply[*v1.EgressService, *v1.EgressServiceList, *egressservicev1.EgressServiceApplyConfiguration](
			"egressservices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.EgressService { return &v1.EgressService{} },
			func() *v1.EgressServiceList { return &v1.EgressServiceList{} }),
	}
}
