// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// removeFunc is an autogenerated mock type for the removeFunc type
type removeFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *removeFunc) Execute(_a0 string) {
	_m.Called(_a0)
}

type mockConstructorTestingTnewRemoveFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newRemoveFunc creates a new instance of removeFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newRemoveFunc(t mockConstructorTestingTnewRemoveFunc) *removeFunc {
	mock := &removeFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
