kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  apiServerAddress: 11.12.13.1
  apiServerPort: 11337
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "SCTPSupport=true"
nodes:
 - role: control-plane
   extraMounts:
     - hostPath: /tmp/kind
       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
 - role: control-plane
   extraMounts:
     - hostPath: /tmp/kind
       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
 - role: control-plane
   extraMounts:
     - hostPath: /tmp/kind
       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
# - role: worker
#   extraMounts:
#     - hostPath: /tmp/kind
#       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/
# - role: worker
#   extraMounts:
#     - hostPath: /tmp/kind
#       containerPath: /var/run/secrets/kubernetes.io/serviceaccount/

