/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	dnsobjectv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/dnsobject/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSObjects implements DNSObjectInterface
type FakeDNSObjects struct {
	Fake *FakeK8sV1
}

var dnsobjectsResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "dnsobjects"}

var dnsobjectsKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1", Kind: "DNSObject"}

// Get takes name of the dNSObject, and returns the corresponding dNSObject object, and an error if there is any.
func (c *FakeDNSObjects) Get(ctx context.Context, name string, options v1.GetOptions) (result *dnsobjectv1.DNSObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dnsobjectsResource, name), &dnsobjectv1.DNSObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*dnsobjectv1.DNSObject), err
}

// List takes label and field selectors, and returns the list of DNSObjects that match those selectors.
func (c *FakeDNSObjects) List(ctx context.Context, opts v1.ListOptions) (result *dnsobjectv1.DNSObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dnsobjectsResource, dnsobjectsKind, opts), &dnsobjectv1.DNSObjectList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &dnsobjectv1.DNSObjectList{ListMeta: obj.(*dnsobjectv1.DNSObjectList).ListMeta}
	for _, item := range obj.(*dnsobjectv1.DNSObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSObjects.
func (c *FakeDNSObjects) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dnsobjectsResource, opts))
}

// Create takes the representation of a dNSObject and creates it.  Returns the server's representation of the dNSObject, and an error, if there is any.
func (c *FakeDNSObjects) Create(ctx context.Context, dNSObject *dnsobjectv1.DNSObject, opts v1.CreateOptions) (result *dnsobjectv1.DNSObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dnsobjectsResource, dNSObject), &dnsobjectv1.DNSObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*dnsobjectv1.DNSObject), err
}

// Update takes the representation of a dNSObject and updates it. Returns the server's representation of the dNSObject, and an error, if there is any.
func (c *FakeDNSObjects) Update(ctx context.Context, dNSObject *dnsobjectv1.DNSObject, opts v1.UpdateOptions) (result *dnsobjectv1.DNSObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dnsobjectsResource, dNSObject), &dnsobjectv1.DNSObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*dnsobjectv1.DNSObject), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSObjects) UpdateStatus(ctx context.Context, dNSObject *dnsobjectv1.DNSObject, opts v1.UpdateOptions) (*dnsobjectv1.DNSObject, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(dnsobjectsResource, "status", dNSObject), &dnsobjectv1.DNSObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*dnsobjectv1.DNSObject), err
}

// Delete takes name of the dNSObject and deletes it. Returns an error if one occurs.
func (c *FakeDNSObjects) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(dnsobjectsResource, name), &dnsobjectv1.DNSObject{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSObjects) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dnsobjectsResource, listOpts)

	_, err := c.Fake.Invokes(action, &dnsobjectv1.DNSObjectList{})
	return err
}

// Patch applies the patch and returns the patched dNSObject.
func (c *FakeDNSObjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *dnsobjectv1.DNSObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dnsobjectsResource, name, pt, data, subresources...), &dnsobjectv1.DNSObject{})
	if obj == nil {
		return nil, err
	}
	return obj.(*dnsobjectv1.DNSObject), err
}
