// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package nbdb

import "github.com/ovn-org/libovsdb/model"

const CoppTable = "Copp"

// Copp defines an object in Copp table
type Copp struct {
	UUID        string            `ovsdb:"_uuid"`
	ExternalIDs map[string]string `ovsdb:"external_ids"`
	Meters      map[string]string `ovsdb:"meters"`
	Name        string            `ovsdb:"name"`
}

func (a *Copp) GetUUID() string {
	return a.UUID
}

func (a *Copp) GetExternalIDs() map[string]string {
	return a.ExternalIDs
}

func copyCoppExternalIDs(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalCoppExternalIDs(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *Copp) GetMeters() map[string]string {
	return a.Meters
}

func copyCoppMeters(a map[string]string) map[string]string {
	if a == nil {
		return nil
	}
	b := make(map[string]string, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}

func equalCoppMeters(a, b map[string]string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || v != w {
			return false
		}
	}
	return true
}

func (a *Copp) GetName() string {
	return a.Name
}

func (a *Copp) DeepCopyInto(b *Copp) {
	*b = *a
	b.ExternalIDs = copyCoppExternalIDs(a.ExternalIDs)
	b.Meters = copyCoppMeters(a.Meters)
}

func (a *Copp) DeepCopy() *Copp {
	b := new(Copp)
	a.DeepCopyInto(b)
	return b
}

func (a *Copp) CloneModelInto(b model.Model) {
	c := b.(*Copp)
	a.DeepCopyInto(c)
}

func (a *Copp) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *Copp) Equals(b *Copp) bool {
	return a.UUID == b.UUID &&
		equalCoppExternalIDs(a.ExternalIDs, b.ExternalIDs) &&
		equalCoppMeters(a.Meters, b.Meters) &&
		a.Name == b.Name
}

func (a *Copp) EqualsModel(b model.Model) bool {
	c := b.(*Copp)
	return a.Equals(c)
}

var _ model.CloneableModel = &Copp{}
var _ model.ComparableModel = &Copp{}
