{
 "title": "OVN K8s / Cluster Manager",
 "description": "K8s Control Panel component : Kube Manager",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "manager_inst",
    "label": "Kube Manager Instance",
    "query": {
     "query": "label_values(ovnkube_clustermanager_build_info, instance)"
    }
   },
   {
    "name": "manager_pod",
    "label": "Kube Manager Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"ovn-kubernetes\",created_by_kind=\"ReplicaSet\",created_by_name=~\"ovnkube-control-plane-.*\"}, pod)"
    }
   },
   { "name": "topk", "label": "topk", "query": "1,3,5,10,20,10000" }
  ]
 },
 "panels": [
  { "title": "Kube Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "INFO",
   "type": "table",
   "description": "Package version info",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ovnkube_clustermanager_build_info{instance=~\"$manager_inst\"}"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "stat",
   "description": "Represents which ovnkube-control-plane pod is leader ",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovnkube_clustermanager_leader", "legendFormat": "{{pod}}:" }
   ]
  },
  {
   "title": "E2E STATUS",
   "type": "stat",
   "description": "Overall cluster E2E status: HEALTY, UPDATING or FAULTED",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ovnkube_controller_nb_e2e_timestamp)"
    },
    {
     "expr": "max(ovnkube_controller_sb_e2e_timestamp)"
    }
   ]
  },
  {
   "title": "AVG OPEN FLOWS (TOP K)",
   "type": "table",
   "description": "Average number of open flows installed per node",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum(ovn_controller_integration_bridge_openflow_total) by (instance))"
    }
   ]
  },
  {
   "title": "MEMORY ",
   "type": "graph",
   "description": "Memory usage within ovnkube-control-plane pod ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", namespace=\"ovn-kubernetes\", pod=~\"$manager_pod\",container=\"ovnkube-cluster-manager\"}) / 1024^3",
     "legendFormat": "ovnkube-cluster-manager"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU rates within ovnkube-control-plane pod containers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"ovn-kubernetes\", pod=~\"$manager_pod\",container=\"ovnkube-cluster-manager\"}[5m]))",
     "legendFormat": "ovnkube-cluster-manager"
    }
   ]
  },
  {
   "title": "SVC SYNC TOTAL (RATE/SEC)",
   "type": "timeseries",
   "description": "Rate of total number of time service sync happens inside cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ovnkube_controller_sync_service_total{instance=~\"$manager_inst\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SVC REQUEUE TOTAL (RATE/SEC)",
   "type": "timeseries",
   "description": "Rate of total number of times a service is requeued after failing to sync with OVN",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ovnkube_controller_requeue_service_total{instance=~\"$manager_inst\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "POD CREATE LATENCY (99th percentile)",
   "type": "graph",
   "description": "The latency between pod creation and setting the OVN annotations",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ovnkube_controller_pod_creation_latency_seconds_bucket{instance=~\"$manager_inst\"}[$__rate_interval])) by (le))",
     "legendFormat": "Latency"
    },
    {
     "expr": "histogram_quantile(0.99,\n sum by (le) (\n    rate(ovnkube_controller_pod_creation_latency_seconds_bucket[$__rate_interval] \n     offset 15m)\n )\n)\n\n-\n\nhistogram_quantile(0.99,\n sum by (le) (\n    rate(ovnkube_controller_pod_creation_latency_seconds_bucket[$__rate_interval])\n )\n) \n",
     "legendFormat": "Difference"
    }
   ]
  },
  {
   "title": "UPDATE RATE/SEC",
   "type": "graph",
   "description": "The rate of a particular resource has been updated with an event",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ovnkube_controller_resource_update_total{instance=~\"$manager_inst\"}[2m])) by (name,event)",
     "legendFormat": "{{name}}-{{event}}"
    }
   ]
  },
  {
   "title": "NUMBER OF LEADERS",
   "type": "graph",
   "description": "Tracks multiple manager leaders and no leader cases",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ovnkube_clustermanager_leader)",
     "legendFormat": "leaders"
    }
   ]
  },
  {
   "title": "KUBE MANAGER LEADERSHIP CHANGES",
   "type": "graph",
   "description": "Tracks how frequently kube manager  leadership changes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "ovnkube_clustermanager_leader", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "LB SERVICE SYNC (99th percentile)",
   "type": "timeseries",
   "description": "The latency of syncing a service with the OVN load balancers",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(ovnkube_controller_sync_service_latency_seconds_bucket{instance=~\"$manager_inst\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "RATE OF LOGFILE CHANGES",
   "type": "timeseries",
   "description": "The rate of change of various logfiles",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ovnkube_controller_logfile_size_bytes{logfile_name=\"ovnkube-cluster-manager.log\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workqueue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "WQ DEPTH",
     "type": "graph",
     "description": "Current depth of manager workqueue",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "clamp_min(ovnkube_controller_workqueue_depth{instance=~\"$manager_inst\"},0)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "WQ ITEMS RATE",
     "type": "graph",
     "description": "Total number of adds handled by workqueue",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(ovnkube_controller_workqueue_adds_total{instance=~\"$manager_inst\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "WQ RETRY ITEMS RATE",
     "type": "graph",
     "description": "Total number of retries handled by workqueue",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(ovnkube_controller_workqueue_retries_total{instance=~\"$manager_inst\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "WQ AVG WORK DURATION",
     "type": "graph",
     "description": "How long processing an item from the work queue takes.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ovnkube_controller_workqueue_work_duration_seconds_sum{instance=~\"$manager_inst\"}[1m]) / rate(ovnkube_controller_workqueue_work_duration_seconds_count{instance=~\"$manager_inst\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "WQ AVG ITEMS DURATION",
     "type": "graph",
     "description": "How long an item stays in the work queue.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ovnkube_controller_workqueue_queue_duration_seconds_sum{instance=~\"$manager_inst\"}[1m]) / rate(ovnkube_controller_workqueue_queue_duration_seconds_count{instance=~\"$manager_inst\"}[1m])) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "WQ LONGEST RUNNING PROCESSOR",
     "type": "graph",
     "description": "How many seconds has the longest running processor for workqueue been running",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "ovnkube_controller_workqueue_longest_running_processor_seconds",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "WQ UNFINISHED/STUCK ITEMS",
     "type": "graph",
     "description": "How many seconds of work has done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "ovnkube_controller_workqueue_unfinished_work_seconds{instance=~\"$manager_inst\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kube Alerts",
     "type": "table",
     "description": "Built-in Prometheus Kube Alerts",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "ALERTS{namespace=\"ovn-kubernetes\",deployment=\"ovnkube-control-plane\", alertstate=\"firing\"}"
      }
     ]
    }
   ]
  }
 ]
}