{
 "title": "OVN Central / North Daemon",
 "description": "OVN Central component : North Daemon",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_inst",
    "label": "Node Instance",
    "query": {
     "query": "label_values(ovn_northd_build_info, instance)"
    }
   },
   {
    "name": "northd_pod",
    "label": "OVN North Daemon Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"ovn-kubernetes\",created_by_kind=\"ReplicaSet\",created_by_name=~\"(ovn-north-.*|ovnkube-master-.*)\"}, pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "North Daemon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB CONN STATUS",
   "type": "bargauge",
   "description": "Connection status of ovn-northd to NB/SB",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ovn_northd_sb_connection_status",
     "legendFormat": "SB:{{instance}}"
    },
    {
     "expr": "ovn_northd_nb_connection_status",
     "legendFormat": "NB:{{instance}}"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "stat",
   "description": "Overall North daemon status: STANDBY, ACTIVE or PAUSED",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovn_northd_status", "legendFormat": " {{pod}} :" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU utilization within ovnkube-north pods",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"ovn-kubernetes\", pod=~\"$northd_pod\",container=\"ovn-northd\"}[5m])",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "timeseries",
   "description": "Memory utilization within ovnkube-north pods",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", namespace=\"ovn-kubernetes\", pod=~\"$northd_pod\",container=\"ovn-northd\"} / 1024^3",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "INFO",
   "type": "table",
   "description": "OVN/OVS versions of software running on the north daemon pod",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ovn_northd_build_info", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CONTAINER RESTARTS",
   "type": "graph",
   "description": "Tracks container restarts for ovn-northd",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"ovn-kubernetes\", pod=~\"ovn-north.*\", container=\"ovn-northd\"}[15m])",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "NORTHD STATUS",
   "type": "graph",
   "description": "Tracks north daemon status",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "ovn_northd_status", "legendFormat": "{{pod}} - {{instance}}" }
   ]
  },
  {
   "title": "TXN INCOMPLETE RATE/SEC",
   "type": "graph",
   "description": "Tracks north daemon txn incomplete rate",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_northd_txn_incomplete{namespace=\"ovn-kubernetes\",job=\"ovnkube-node\",instance=~\"$node_inst\"}[5m])",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "TXN ERROR RATE/SEC",
   "type": "graph",
   "description": "Tracks north daemon txn error rate",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_northd_txn_error{namespace=\"ovn-kubernetes\",job=\"ovnkube-node\",instance=~\"$node_inst\"}[5m])",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "North Daemon Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "PSTREAM_OPEN RATE/SEC",
     "type": "graph",
     "description": "Specifies the number of time passive connections were opened for the remote peer to connect.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ovn_northd_pstream_open{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "STREAM_OPEN RATE/SEC",
     "type": "graph",
     "description": "Specifies the number of attempts to connect to a remote peer (active connection).",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ovn_northd_stream_open{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TXN_SUCCESS RATE/SEC",
     "type": "graph",
     "description": "Specifies the number of times the OVSDB transaction has successfully completed.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ovn_northd_txn_success{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TXN DETAILS RATE/SEC",
     "type": "graph",
     "description": "Other conditions that are related to ongoing OVSDB transactions",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ovn_northd_txn_aborted{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "aborted,{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_txn_error{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "error,{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_txn_try_again{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "try_again,{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_txn_unchanged{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "unchanged,{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_txn_uncommitted{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "uncommitted,{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_txn_incomplete{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "incomplete,{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "North Daemon Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "95TH_PERCENTILE",
     "type": "timeseries",
     "description": "Stopwatch performance counter",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ovn_northd_build_lflows_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-{{instance}}"
      },
      {
       "expr": "ovn_northd_clear_lflows_ctx_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "clear-lflows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_build_flows_ctx_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "flows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_datapaths_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-datapath-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_dp_groups_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-dp-groups-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_igmp_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-igmp-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_lbs_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-lbs-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_ports_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-ports-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovn_northd_loop_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "northd_loop-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnnb_db_run_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "ovnnb-db-run-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnsb_db_run_95th_percentile{instance=~\"$node_inst\"}",
       "legendFormat": "ovnsb-db-run-{{instance}}"
      }
     ]
    },
    {
     "title": "TOTAL_SAMPLES RATE/SEC",
     "type": "timeseries",
     "description": "Stopwatch performance counter",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ovn_northd_build_lflows_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "lflows-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_clear_lflows_ctx_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "clear-lflows-ctx-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_build_flows_ctx_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "flows-ctx-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_lflows_datapaths_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "lflows-datapath-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_lflows_dp_groups_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "lflows-dp-groups-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_lflows_igmp_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "lflows-igmp-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_lflows_lbs_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "lflows-lbs-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_lflows_ports_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "lflows-ports-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_ovn_northd_loop_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "northd_loop-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_ovnnb_db_run_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "ovnnb-db-run-{{instance}}"
      },
      {
       "expr": "rate(ovn_northd_ovnsb_db_run_total_samples{instance=~\"$node_inst\"}[5m])",
       "legendFormat": "ovnsb-db-run-{{instance}}"
      }
     ]
    },
    {
     "title": "MINIMUM",
     "type": "timeseries",
     "description": "Stopwatch performance counter",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ovn_northd_build_lflows_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-{{instance}}"
      },
      {
       "expr": "ovn_northd_clear_lflows_ctx_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "clear-lflows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_build_flows_ctx_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "flows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_datapaths_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-datapath-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_dp_groups_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-dp-groups-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_igmp_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-igmp-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_lbs_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-lbs-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_ports_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-ports-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovn_northd_loop_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "northd_loop-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnnb_db_run_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "ovnnb-db-run-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnsb_db_run_minimum{instance=~\"$node_inst\"}",
       "legendFormat": "ovnsb-db-run-{{instance}}"
      }
     ]
    },
    {
     "title": "MAXIMUM",
     "type": "timeseries",
     "description": "Stopwatch performance counter",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ovn_northd_build_lflows_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-{{instance}}"
      },
      {
       "expr": "ovn_northd_clear_lflows_ctx_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "clear-lflows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_build_flows_ctx_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "flows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_datapaths_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-datapath-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_dp_groups_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-dp-groups-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_igmp_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-igmp-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_lbs_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-lbs-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_ports_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-ports-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovn_northd_loop_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "northd_loop-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnnb_db_run_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "ovnnb-db-run-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnsb_db_run_maximum{instance=~\"$node_inst\"}",
       "legendFormat": "ovnsb-db-run-{{instance}}"
      }
     ]
    },
    {
     "title": "SHORT_TERM_AVG",
     "type": "timeseries",
     "description": "Stopwatch performance counter",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ovn_northd_build_lflows_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-{{instance}}"
      },
      {
       "expr": "ovn_northd_clear_lflows_ctx_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "clear-lflows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_build_flows_ctx_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "flows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_datapaths_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-datapath-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_dp_groups_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-dp-groups-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_igmp_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-igmp-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_lbs_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-lbs-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_ports_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-ports-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovn_northd_loop_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "northd_loop-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnnb_db_run_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "ovnnb-db-run-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnsb_db_run_short_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "ovnsb-db-run-{{instance}}"
      }
     ]
    },
    {
     "title": "LONG_TERM_AVG",
     "type": "timeseries",
     "description": "Stopwatch performance counter",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ovn_northd_build_lflows_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-{{instance}}"
      },
      {
       "expr": "ovn_northd_clear_lflows_ctx_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "clear-lflows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_build_flows_ctx_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "flows-ctx-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_datapaths_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-datapath-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_dp_groups_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-dp-groups-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_igmp_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-igmp-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_lbs_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-lbs-{{instance}}"
      },
      {
       "expr": "ovn_northd_lflows_ports_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "lflows-ports-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovn_northd_loop_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "northd_loop-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnnb_db_run_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "ovnnb-db-run-{{instance}}"
      },
      {
       "expr": "ovn_northd_ovnsb_db_run_long_term_avg{instance=~\"$node_inst\"}",
       "legendFormat": "ovnsb-db-run-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kube Alerts",
     "type": "table",
     "description": "Built-in Prometheus Kube Alerts",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "ALERTS{namespace=\"ovn-kubernetes\",deployment=\"ovn-north\"}"
      }
     ]
    }
   ]
  }
 ]
}