{
 "title": "OVN K8s / Node Agent",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_pod",
    "label": "Node Pod",
    "query": {
     "query": "label_values(ovnkube_node_build_info, pod)"
    }
   },
   { "name": "topk", "label": "topk", "query": "1,3,5,10,20,100,1000" }
  ]
 },
 "panels": [
  {
   "title": "Kube Node DaemonSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AGENT STATUS",
   "type": "bargauge",
   "description": "Shows summary of ovnkube-node pods that are ready",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"}",
     "legendFormat": "READY"
    },
    {
     "expr": "kube_daemonset_status_number_available{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"} + kube_daemonset_status_number_unavailable{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"} - kube_daemonset_status_number_ready{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"}",
     "legendFormat": "NOT READY"
    }
   ]
  },
  {
   "title": "OVNKUBE-NODE PODS",
   "type": "bargauge",
   "description": "shows summary of available and unavailabe ovnkube-node pods",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"}",
     "legendFormat": "AVAILABLE"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"}",
     "legendFormat": "UNAVAILABLE"
    }
   ]
  },
  {
   "title": "HOST MEMORY USAGE (TOP K)",
   "type": "timeseries",
   "description": "Average Memory usage of top 10 of ovnkube-node pods",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($topk,max(container_memory_working_set_bytes{namespace=\"ovn-kubernetes\", pod=~\"$node_pod\",pod!~\"ovnkube-node-dpu-.*\"}) by (pod))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "topk($topk,max(container_memory_working_set_bytes{namespace=\"ovn-kubernetes\", pod=~\"$node_pod\",pod=~\"ovnkube-node-dpu-host.*\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HOST MEMORY USAGE RATE/SEC (TOP K)",
   "type": "timeseries",
   "description": "Average Memory usage of top K of ovnkube-node and ovnkube-node-dpu-host pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($topk,max(rate(container_memory_working_set_bytes{namespace=\"ovn-kubernetes\",pod=~\"$node_pod\",pod!~\"ovnkube-node-dpu-.*\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "topk($topk,max(rate(container_memory_working_set_bytes{namespace=\"ovn-kubernetes\",pod=~\"$node_pod\",pod=~\"ovnkube-node-dpu-host.*\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WORKQUEUE WORK (99 percentile)",
   "type": "timeseries",
   "description": "Time taken by an item between staying in workqueue and being requested",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum(rate(ovnkube_node_workqueue_queue_duration_seconds_bucket[2m])) by (le)))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "RATE OF LOGFILE CHANGES",
   "type": "timeseries",
   "description": "The rate of change of various logfiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ovnkube_node_logfile_size_bytes{logfile_name=\"ovnkube.log\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HOST CPU USAGE/SEC (TOP K)",
   "type": "timeseries",
   "description": "Average of top 10 CPU usage of all containers in ovnkube-node pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "topk($topk, rate(container_cpu_usage_seconds_total{namespace=\"ovn-kubernetes\", pod=~\"$node_pod\", pod!~\".*-dpu-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TOPK CNI REQUEST",
   "type": "graph",
   "description": "99th percentile of CNI requests grouped by command",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk($topk,histogram_quantile(0.99, rate(ovnkube_node_cni_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{command}}-{{pod}}"
    }
   ]
  },
  {
   "title": "BUILD INFO",
   "type": "table",
   "description": "Build info for OVN controller",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ovn_controller_build_info{pod=~\"$node_pod\"}"
    }
   ]
  },
  {
   "title": "BUILD STATUS",
   "type": "stat",
   "description": "Status of OVN Controllers component in cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_values(\"version\", ovn_controller_build_info{pod=~\"$node_pod\"}))"
    }
   ]
  },
  {
   "title": "CONTAINER RESTARTS",
   "type": "graph",
   "description": "Tracks container restarts for ovnkube-node containers",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"ovn-kubernetes\",container=~\".*ovnkube-node.*\"}[15m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube Alerts",
   "type": "table",
   "description": "Built-in Prometheus Kube Alerts",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "ALERTS{namespace=\"ovn-kubernetes\",daemonset=\"ovnkube-node\"}"
    }
   ]
  }
 ]
}