{
 "title": "OVN Host / Controller",
 "description": "OVN Host component : Controller",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node_inst",
    "label": "Node Instance",
    "query": {
     "query": "label_values(ovn_controller_build_info, instance)"
    }
   },
   {
    "name": "host_pod",
    "label": "Host Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"ovn-kubernetes\",created_by_kind=\"DaemonSet\",created_by_name=~\"(ovn-host|ovnkube-node)\"}, pod)"
    }
   },
   { "name": "topk", "label": "topk", "query": "1,3,5,10,20,10000" }
  ]
 },
 "panels": [
  {
   "title": "Host Controller DaemonSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO",
   "type": "table",
   "description": "OVN/OVS versions of software",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ovn_controller_build_info", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CONTROLLER CONNECTION STATUS",
   "type": "bargauge",
   "description": "Connection status of ovn-node pods to southbound pods",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ovn_controller_southbound_database_connected{namespace=\"ovn-kubernetes\"})",
     "legendFormat": "CONNECTED"
    },
    {
     "expr": "sum(1 - ovn_controller_southbound_database_connected{namespace=\"ovn-kubernetes\"})",
     "legendFormat": "NOT CONNECTED"
    }
   ]
  },
  {
   "title": "HOST PODS STATUS",
   "type": "bargauge",
   "description": "Available ovn-node pods",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=\"ovn-kubernetes\",daemonset=~\"(ovn-host|ovnkube-node)\"}",
     "legendFormat": "AVAILABLE"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{namespace=\"ovn-kubernetes\",daemonset=~\"(ovn-host|ovnkube-node)\"}",
     "legendFormat": "UNAVAILABLE"
    }
   ]
  },
  {
   "title": "OVN HOST CPU USAGE (TOP $topk)",
   "type": "timeseries",
   "description": "Memory usage of top $topk of OVN Host pods",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "topk($topk,rate(container_cpu_usage_seconds_total{namespace=\"ovn-kubernetes\", pod=~\"$host_pod\",container=\"ovn-controller\"}[5m]))",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "LFLOW RUN RATE/SEC",
   "type": "graph",
   "description": "Tracks controllers lflow run rate",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_controller_lflow_run{namespace=\"ovn-kubernetes\",job=\"ovnkube-node\",instance=~\"$node_inst.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "OVN HOST MEMORY USAGE (TOP $topk)",
   "type": "graph",
   "description": "Memory usage of top $topk of OVN Host pods",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk($topk,max(container_memory_working_set_bytes{namespace=\"ovn-kubernetes\", pod=~\"$host_pod\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TXN INCOMPLETE RATE/SEC",
   "type": "graph",
   "description": "Tracks controller txn incomplete rate",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_controller_txn_incomplete{namespace=\"ovn-kubernetes\",job=\"ovnkube-node\",instance=~\"$node_inst.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "OVN HOST CPU USAGE/SEC (SUM PER THREAD)",
   "type": "timeseries",
   "description": "Memory usage of top $topk of OVN Host pods",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_thread_cpu_seconds_total{instance=~\"$node_inst.*\",groupname=\"ovn-controller\",job=\"process-exporter\",threadname=~\".+\"}[$__rate_interval])) by (threadname)",
     "legendFormat": "{{threadname}}"
    }
   ]
  },
  {
   "title": "TXN ERROR RATE/SEC",
   "type": "graph",
   "description": "Tracks controller txn error rate",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_controller_txn_error{namespace=\"ovn-kubernetes\",job=\"ovnkube-node\",instance=~\"$node_inst.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "CONTAINER RESTARTS (TOP $topk)",
   "type": "graph",
   "description": "Tracks container restarts for ovn-controller",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(kube_pod_container_status_restarts_total{namespace=\"ovn-kubernetes\", pod=~\"(^ovn-host-.*|ovnkube-node-.*)\",container=\"ovn-controller\"}[15m]))",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Controller Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOTAL TXN SUCCESS (RATE/SEC)",
   "type": "stat",
   "description": "Total successful transactions across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ovn_controller_txn_success{instance=~\"$node_inst.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "TOTAL TXN UNCHANGED (RATE/SEC)",
   "type": "stat",
   "description": "Total transactions that are resulted in no change to a database across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ovn_controller_txn_unchanged{instance=~\"$node_inst.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "TXN SUCCESS RATE/SEC (TOP $topk)",
   "type": "graph",
   "description": "rate of successful transactions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_success{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "TXN INCOMPLETE RATE/SEC (TOP $topk)",
   "type": "graph",
   "description": "rate of increase of incomplete transactions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_incomplete{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "TXN UNCHANGED RATE/SEC (TOP $topk)",
   "type": "graph",
   "description": "rate of increase of unchanged transactions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_txn_unchanged{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "TXN SUCCESS (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of times the OVSDB transaction has successfully completed",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, ovn_controller_txn_success{instance=~\"$node_inst.*\"})",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "TXN ABNORMAL (TOP $topk)",
   "type": "graph",
   "description": "Top $topk transactions that are  abnormal: error, aborted, try_again, uncommitted",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, ovn_controller_txn_error{instance=~\"$node_inst.*\"})",
     "legendFormat": "error,  {{instance}}, {{pod}}"
    },
    {
     "expr": "topk($topk, ovn_controller_txn_aborted{instance=~\"$node_inst.*\"})",
     "legendFormat": "aborted, {{instance}}, {{pod}}"
    },
    {
     "expr": "topk($topk, ovn_controller_txn_try_again{instance=~\"$node_inst.*\"})",
     "legendFormat": "try_again, {{instance}}, {{pod}}"
    },
    {
     "expr": "topk($topk, ovn_controller_txn_uncommitted{instance=~\"$node_inst.*\"})",
     "legendFormat": "uncommitted, {{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "TXN INCOMPLETE (TOP $topk)",
   "type": "graph",
   "description": "Number of transactions that haven't completed yet.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, ovn_controller_txn_incomplete{instance=~\"$node_inst.*\"})",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "TXN UNCHANGED (TOP $topk)",
   "type": "graph",
   "description": "Number of transactions that don't change the OVS DB.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, ovn_controller_txn_unchanged{instance=~\"$node_inst.*\"})",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RCONN QUEUED/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of messages that have been  queued because it couldn’t be sent using the  underlying virtual connection to OpenFlow devices per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_rconn_queued{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "RCONN_OVERFLOW/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of messages that have been dropped because of the queue overflow per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_rconn_overflow{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "RCONN_SENT/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of messages that have been sent to the underlying virtual  connection (unix, tcp, or ssl) to OpenFlow devices.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_rconn_sent{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "RCONN_DISCARDED/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of messages that  have been dropped because the send queue had to be flushed because of reconnection per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_rconn_discarded{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "VCONN_SENT/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of messages sent to the OpenFlow Device.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_vconn_sent{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "VCONN_RECEIVED/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of messages received  from the OpenFlow Device per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_vconn_received{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "VCONN_OPEN/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of attempts to connect  to a remote peer (active connection) per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_vconn_open{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "STREAM_OPEN/SEC (TOP $topk)",
   "type": "graph",
   "description": "Specifies the number of attempts to connect to a remote peer (active connection) per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_stream_open{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Open Flow Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {}
   ]
  },
  {
   "title": "LFLOW RUN/SEC (TOP $topk)",
   "type": "graph",
   "description": "Number of times ovn-controller has translated the Logical_Flow table in the OVN SB database into OpenFlow flows per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($topk, rate(ovn_controller_lflow_run{instance=~\"$node_inst.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube Alerts",
   "type": "table",
   "description": "Built-in Prometheus Kube Alerts",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "ALERTS{namespace=\"ovn-kubernetes\",daemonset=~\"(ovn-host|ovnkube-node)\"}"
    },
    {
     "expr": "ALERTS{namespace=\"ovn-kubernetes\",daemonset=\"ovn-host-dpu\"}"
    }
   ]
  }
 ]
}