{
 "title": "OVN Central / Southbound DB",
 "description": "OVN Central component : Southbound DB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_pod",
    "label": "Node Pod",
    "query": {
     "query": "label_values(ovn_db_build_info, pod)"
    }
   },
   {
    "name": "sbdb_pod",
    "label": "Southbound DB Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"ovn-kubernetes\",created_by_kind=\"StatefulSet\",created_by_name=~\"(ovn-sbdb|ovnkube-db.*)\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Southbound DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "INFO",
   "type": "table",
   "description": "Southbound OVSDB related info",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ovn_db_build_info{pod=~\"$node_pod\"}"
    },
    {
     "expr": "ovn_db_cluster_id{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}"
    }
   ]
  },
  {
   "title": "DB SIZE",
   "type": "timeseries",
   "description": "The size of Southbound database",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ovn_db_db_size_bytes{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}",
     "legendFormat": "{{pod}}-{{instance}}"
    }
   ]
  },
  {
   "title": "DB MONITORS",
   "type": "timeseries",
   "description": "Active Southbound DB Monitors",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ovn_db_ovsdb_monitors{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}",
     "legendFormat": "{{pod}}-{{instance}}"
    }
   ]
  },
  {
   "title": "RPC SESSIONS",
   "type": "stat",
   "description": "Active number of JSON RPC Server sessions to the Southbound DB",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ovn_db_jsonrpc_server_sessions{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Average rate of CPU utilization within ovn-sbdb pods",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\", namespace=\"ovn-kubernetes\", pod=~\"$sbdb_pod\", container=~\"(sbdb|sb-ovsdb)\"}[15m])",
     "legendFormat": "{{pod}}-{{container}}-{{instance}}"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "timeseries",
   "description": "Memory utilization within ovn-sbdb pods",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", namespace=\"ovn-kubernetes\", pod=~\"$sbdb_pod\", container=~\"(sbdb|sb-ovsdb)\"} / 1024^3",
     "legendFormat": "{{pod}}-{{container}}-{{instance}}"
    }
   ]
  },
  {
   "title": "CONN. ERRORS",
   "type": "bargauge",
   "description": "In/Out Southbound OVSDB connections errors",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ovn_db_cluster_inbound_connections_error_total{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"})",
     "legendFormat": "In Err"
    },
    {
     "expr": "sum(ovn_db_cluster_outbound_connections_error_total{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"})",
     "legendFormat": "Out Err"
    }
   ]
  },
  {
   "title": "LOG ACTIVITY",
   "type": "bargauge",
   "description": "Southbound OVSDB Log activity",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ovn_db_cluster_log_not_applied{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"})",
     "legendFormat": "Not Applied"
    },
    {
     "expr": "sum(ovn_db_cluster_log_not_committed{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"})",
     "legendFormat": "Not Committed"
    }
   ]
  },
  {
   "title": "RAFT STATUS",
   "type": "table",
   "description": "Cumulative RAFT status table for Southbound OVSDB",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(ovn_db_cluster_server_status{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}) by (pod,server_id,server_status)"
    },
    {
     "expr": "sum(ovn_db_cluster_server_role{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}) by (pod,server_role)"
    },
    {
     "expr": "sum(ovn_db_cluster_log_index_start{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}) by (pod)"
    },
    {
     "expr": "sum(ovn_db_cluster_log_index_next{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}) by (pod)"
    },
    {
     "expr": "sum(ovn_db_cluster_server_vote{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}) by (pod,server_vote)"
    },
    {
     "expr": "sum(ovn_db_cluster_term{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}) by (pod)"
    }
   ]
  },
  {
   "title": "SERVER ROLES",
   "type": "status-history",
   "description": "Tracks graphs of server roles",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ovn_db_cluster_server_role{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}",
     "legendFormat": "{{server_role}}-{{instance}}"
    }
   ]
  },
  {
   "title": "E2E NORTHD STALL",
   "type": "timeseries",
   "description": "Tracks e2e check for Southbound NorthD stalls",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "abs(max(ovnkube_master_nb_e2e_timestamp)-max(ovnkube_master_sb_e2e_timestamp))",
     "legendFormat": "e2e-difference"
    }
   ]
  },
  {
   "title": "RATE OF RAFT LOG TERM CHANGES/SEC",
   "type": "timeseries",
   "description": "Tracks rate of RAFT log changes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ovn_db_cluster_term{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "term-{{instance}}"
    }
   ]
  },
  {
   "title": "RATE OF RAFT LOG START/NEXT CHANGES/SEC",
   "type": "timeseries",
   "description": "Tracks rate of RAFT log changes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ovn_db_cluster_log_index_start{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "log_start-{{instance}}"
    },
    {
     "expr": "rate(ovn_db_cluster_log_index_next{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "log_next-{{instance}}"
    }
   ]
  },
  {
   "title": "CONTAINER RESTARTS",
   "type": "timeseries",
   "description": "Tracks container restarts for ovn-sbdb sts",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"ovn-kubernetes\", container=~\"(sbdb|sb-ovsdb)\",pod=~\"(ovn-sbdb-.*|ovnkube-db-.*)\"}[15m])",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  { "title": "Southbound DB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "RATE PSTREAM_OPEN/SEC",
   "type": "timeseries",
   "description": "Specifies the number of time passive connections were opened for the remote peer to connect.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ovn_db_pstream_open{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RATE STREAM_OPEN/SEC",
   "type": "graph",
   "description": "Specifies the number of attempts to connect to a remote peer (active connection).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_db_stream_open{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RATE HMAP DETAILS/SEC",
   "type": "timeseries",
   "description": "Registering how many hash map resize calls has been made",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ovn_db_hmap_pathological{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "heavy resizes-{{instance}}"
    },
    {
     "expr": "rate(ovn_db_hmap_expand{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "expands-{{instance}}"
    }
   ]
  },
  {
   "title": "JSONRPC_SESSIONS",
   "type": "timeseries",
   "description": "Active number of JSON RPC Server sessions to the  Southbound OVSDB",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ovn_db_jsonrpc_server_sessions{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RATE EVENT LOOP BUSY FACTOR/SEC",
   "type": "timeseries",
   "description": "How many scheduled events to wake up blocking poller (event loop busy factor)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ovn_db_poll_create_node{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "EVENT LOOP IDLE FACTOR",
   "type": "timeseries",
   "description": "How many scheduled events were processed without timeout (event loop effectiveness)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ovn_db_poll_zero_timeout{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RATE OBJECT ACTIVITY/SEC",
   "type": "timeseries",
   "description": "Registering intensity of new objects creations",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ovn_db_seq_change{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LOCKFILE_LOCKS",
   "type": "graph",
   "description": "Registering how many expensive file locking has been made",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ovn_db_lockfile_lock{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"})",
     "legendFormat": "lockfile_lock"
    }
   ]
  },
  {
   "title": "ovn_db_util_xalloc",
   "type": "timeseries",
   "description": "Registering intensity of memory allocations in OVSDB server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ovn_db_util_xalloc{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ovn_db_unixctl_replied",
   "type": "graph",
   "description": "Shows how many JSON RPC requests actually processed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ovn_db_unixctl_received{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "received-{{instance}}"
    },
    {
     "expr": "rate(ovn_db_unixctl_replied{db_name=\"OVN_Southbound\",pod=~\"$node_pod\"}[$__rate_interval])",
     "legendFormat": "replied-{{instance}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kube Alerts",
     "type": "table",
     "description": "Built-in Prometheus Kube Alerts",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "ALERTS{namespace=\"ovn-kubernetes\",statefulset=\"ovn-sbdb\"}"
      }
     ]
    }
   ]
  }
 ]
}