// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	kube "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/kube"
	mock "github.com/stretchr/testify/mock"
)

// Annotator is an autogenerated mock type for the Annotator type
type Annotator struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *Annotator) Delete(key string) {
	_m.Called(key)
}

// Run provides a mock function with given fields:
func (_m *Annotator) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *Annotator) Set(key string, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWithFailureHandler provides a mock function with given fields: key, value, failFn
func (_m *Annotator) SetWithFailureHandler(key string, value interface{}, failFn kube.FailureHandlerFn) error {
	ret := _m.Called(key, value, failFn)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, kube.FailureHandlerFn) error); ok {
		r0 = rf(key, value, failFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
