// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileSystemOps is an autogenerated mock type for the FileSystemOps type
type FileSystemOps struct {
	mock.Mock
}

// Readlink provides a mock function with given fields: path
func (_m *FileSystemOps) Readlink(path string) (string, error) {
	ret := _m.Called(path)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFileSystemOps interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileSystemOps creates a new instance of FileSystemOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileSystemOps(t mockConstructorTestingTNewFileSystemOps) *FileSystemOps {
	mock := &FileSystemOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
