// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// NETOps is an autogenerated mock type for the NETOps type
type NETOps struct {
	mock.Mock
}

// InterfaceAddrs provides a mock function with given fields:
func (_m *NETOps) InterfaceAddrs() ([]net.Addr, error) {
	ret := _m.Called()

	var r0 []net.Addr
	if rf, ok := ret.Get(0).(func() []net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
