/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	podnetworkv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/podnetwork/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodNetworks implements PodNetworkInterface
type FakePodNetworks struct {
	Fake *FakeK8sV1
	ns   string
}

var podnetworksResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "podnetworks"}

var podnetworksKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1", Kind: "PodNetwork"}

// Get takes name of the podNetwork, and returns the corresponding podNetwork object, and an error if there is any.
func (c *FakePodNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *podnetworkv1.PodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(podnetworksResource, c.ns, name), &podnetworkv1.PodNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podnetworkv1.PodNetwork), err
}

// List takes label and field selectors, and returns the list of PodNetworks that match those selectors.
func (c *FakePodNetworks) List(ctx context.Context, opts v1.ListOptions) (result *podnetworkv1.PodNetworkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(podnetworksResource, podnetworksKind, c.ns, opts), &podnetworkv1.PodNetworkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &podnetworkv1.PodNetworkList{ListMeta: obj.(*podnetworkv1.PodNetworkList).ListMeta}
	for _, item := range obj.(*podnetworkv1.PodNetworkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podNetworks.
func (c *FakePodNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(podnetworksResource, c.ns, opts))

}

// Create takes the representation of a podNetwork and creates it.  Returns the server's representation of the podNetwork, and an error, if there is any.
func (c *FakePodNetworks) Create(ctx context.Context, podNetwork *podnetworkv1.PodNetwork, opts v1.CreateOptions) (result *podnetworkv1.PodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(podnetworksResource, c.ns, podNetwork), &podnetworkv1.PodNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podnetworkv1.PodNetwork), err
}

// Update takes the representation of a podNetwork and updates it. Returns the server's representation of the podNetwork, and an error, if there is any.
func (c *FakePodNetworks) Update(ctx context.Context, podNetwork *podnetworkv1.PodNetwork, opts v1.UpdateOptions) (result *podnetworkv1.PodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(podnetworksResource, c.ns, podNetwork), &podnetworkv1.PodNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podnetworkv1.PodNetwork), err
}

// Delete takes name of the podNetwork and deletes it. Returns an error if one occurs.
func (c *FakePodNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(podnetworksResource, c.ns, name, opts), &podnetworkv1.PodNetwork{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(podnetworksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &podnetworkv1.PodNetworkList{})
	return err
}

// Patch applies the patch and returns the patched podNetwork.
func (c *FakePodNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *podnetworkv1.PodNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(podnetworksResource, c.ns, name, pt, data, subresources...), &podnetworkv1.PodNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*podnetworkv1.PodNetwork), err
}
