/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/routeadvertisements/v1"
	routeadvertisementsv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/routeadvertisements/v1/apis/applyconfiguration/routeadvertisements/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRouteAdvertisementses implements RouteAdvertisementsInterface
type FakeRouteAdvertisementses struct {
	Fake *FakeK8sV1
}

var routeadvertisementsesResource = v1.SchemeGroupVersion.WithResource("routeadvertisementses")

var routeadvertisementsesKind = v1.SchemeGroupVersion.WithKind("RouteAdvertisements")

// Get takes name of the routeAdvertisements, and returns the corresponding routeAdvertisements object, and an error if there is any.
func (c *FakeRouteAdvertisementses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RouteAdvertisements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(routeadvertisementsesResource, name), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}

// List takes label and field selectors, and returns the list of RouteAdvertisementses that match those selectors.
func (c *FakeRouteAdvertisementses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RouteAdvertisementsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(routeadvertisementsesResource, routeadvertisementsesKind, opts), &v1.RouteAdvertisementsList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RouteAdvertisementsList{ListMeta: obj.(*v1.RouteAdvertisementsList).ListMeta}
	for _, item := range obj.(*v1.RouteAdvertisementsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested routeAdvertisementses.
func (c *FakeRouteAdvertisementses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(routeadvertisementsesResource, opts))
}

// Create takes the representation of a routeAdvertisements and creates it.  Returns the server's representation of the routeAdvertisements, and an error, if there is any.
func (c *FakeRouteAdvertisementses) Create(ctx context.Context, routeAdvertisements *v1.RouteAdvertisements, opts metav1.CreateOptions) (result *v1.RouteAdvertisements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(routeadvertisementsesResource, routeAdvertisements), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}

// Update takes the representation of a routeAdvertisements and updates it. Returns the server's representation of the routeAdvertisements, and an error, if there is any.
func (c *FakeRouteAdvertisementses) Update(ctx context.Context, routeAdvertisements *v1.RouteAdvertisements, opts metav1.UpdateOptions) (result *v1.RouteAdvertisements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(routeadvertisementsesResource, routeAdvertisements), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRouteAdvertisementses) UpdateStatus(ctx context.Context, routeAdvertisements *v1.RouteAdvertisements, opts metav1.UpdateOptions) (*v1.RouteAdvertisements, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(routeadvertisementsesResource, "status", routeAdvertisements), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}

// Delete takes name of the routeAdvertisements and deletes it. Returns an error if one occurs.
func (c *FakeRouteAdvertisementses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(routeadvertisementsesResource, name, opts), &v1.RouteAdvertisements{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRouteAdvertisementses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(routeadvertisementsesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RouteAdvertisementsList{})
	return err
}

// Patch applies the patch and returns the patched routeAdvertisements.
func (c *FakeRouteAdvertisementses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RouteAdvertisements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(routeadvertisementsesResource, name, pt, data, subresources...), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied routeAdvertisements.
func (c *FakeRouteAdvertisementses) Apply(ctx context.Context, routeAdvertisements *routeadvertisementsv1.RouteAdvertisementsApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RouteAdvertisements, err error) {
	if routeAdvertisements == nil {
		return nil, fmt.Errorf("routeAdvertisements provided to Apply must not be nil")
	}
	data, err := json.Marshal(routeAdvertisements)
	if err != nil {
		return nil, err
	}
	name := routeAdvertisements.Name
	if name == nil {
		return nil, fmt.Errorf("routeAdvertisements.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(routeadvertisementsesResource, *name, types.ApplyPatchType, data), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeRouteAdvertisementses) ApplyStatus(ctx context.Context, routeAdvertisements *routeadvertisementsv1.RouteAdvertisementsApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RouteAdvertisements, err error) {
	if routeAdvertisements == nil {
		return nil, fmt.Errorf("routeAdvertisements provided to Apply must not be nil")
	}
	data, err := json.Marshal(routeAdvertisements)
	if err != nil {
		return nil, err
	}
	name := routeAdvertisements.Name
	if name == nil {
		return nil, fmt.Errorf("routeAdvertisements.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(routeadvertisementsesResource, *name, types.ApplyPatchType, data, "status"), &v1.RouteAdvertisements{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RouteAdvertisements), err
}
