// Code generated by mockery v2.43.2. DO NOT EDIT.

package exec

import mock "github.com/stretchr/testify/mock"

// ExitError is an autogenerated mock type for the ExitError type
type ExitError struct {
	mock.Mock
}

type ExitError_Expecter struct {
	mock *mock.Mock
}

func (_m *ExitError) EXPECT() *ExitError_Expecter {
	return &ExitError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields:
func (_m *ExitError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ExitError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ExitError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *ExitError_Expecter) Error() *ExitError_Error_Call {
	return &ExitError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *ExitError_Error_Call) Run(run func()) *ExitError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExitError_Error_Call) Return(_a0 string) *ExitError_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExitError_Error_Call) RunAndReturn(run func() string) *ExitError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// ExitStatus provides a mock function with given fields:
func (_m *ExitError) ExitStatus() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExitStatus")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ExitError_ExitStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExitStatus'
type ExitError_ExitStatus_Call struct {
	*mock.Call
}

// ExitStatus is a helper method to define mock.On call
func (_e *ExitError_Expecter) ExitStatus() *ExitError_ExitStatus_Call {
	return &ExitError_ExitStatus_Call{Call: _e.mock.On("ExitStatus")}
}

func (_c *ExitError_ExitStatus_Call) Run(run func()) *ExitError_ExitStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExitError_ExitStatus_Call) Return(_a0 int) *ExitError_ExitStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExitError_ExitStatus_Call) RunAndReturn(run func() int) *ExitError_ExitStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Exited provides a mock function with given fields:
func (_m *ExitError) Exited() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Exited")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExitError_Exited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exited'
type ExitError_Exited_Call struct {
	*mock.Call
}

// Exited is a helper method to define mock.On call
func (_e *ExitError_Expecter) Exited() *ExitError_Exited_Call {
	return &ExitError_Exited_Call{Call: _e.mock.On("Exited")}
}

func (_c *ExitError_Exited_Call) Run(run func()) *ExitError_Exited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExitError_Exited_Call) Return(_a0 bool) *ExitError_Exited_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExitError_Exited_Call) RunAndReturn(run func() bool) *ExitError_Exited_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *ExitError) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ExitError_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type ExitError_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *ExitError_Expecter) String() *ExitError_String_Call {
	return &ExitError_String_Call{Call: _e.mock.On("String")}
}

func (_c *ExitError_String_Call) Run(run func()) *ExitError_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExitError_String_Call) Return(_a0 string) *ExitError_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExitError_String_Call) RunAndReturn(run func() string) *ExitError_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewExitError creates a new instance of ExitError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExitError(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExitError {
	mock := &ExitError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
