/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	adminpolicybasedroutev1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpolicybasedroute/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAdminPolicyBasedExternalRoutes implements AdminPolicyBasedExternalRouteInterface
type FakeAdminPolicyBasedExternalRoutes struct {
	Fake *FakeK8sV1
}

var adminpolicybasedexternalroutesResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "adminpolicybasedexternalroutes"}

var adminpolicybasedexternalroutesKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1", Kind: "AdminPolicyBasedExternalRoute"}

// Get takes name of the adminPolicyBasedExternalRoute, and returns the corresponding adminPolicyBasedExternalRoute object, and an error if there is any.
func (c *FakeAdminPolicyBasedExternalRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(adminpolicybasedexternalroutesResource, name), &adminpolicybasedroutev1.AdminPolicyBasedExternalRoute{})
	if obj == nil {
		return nil, err
	}
	return obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRoute), err
}

// List takes label and field selectors, and returns the list of AdminPolicyBasedExternalRoutes that match those selectors.
func (c *FakeAdminPolicyBasedExternalRoutes) List(ctx context.Context, opts v1.ListOptions) (result *adminpolicybasedroutev1.AdminPolicyBasedExternalRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(adminpolicybasedexternalroutesResource, adminpolicybasedexternalroutesKind, opts), &adminpolicybasedroutev1.AdminPolicyBasedExternalRouteList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &adminpolicybasedroutev1.AdminPolicyBasedExternalRouteList{ListMeta: obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRouteList).ListMeta}
	for _, item := range obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested adminPolicyBasedExternalRoutes.
func (c *FakeAdminPolicyBasedExternalRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(adminpolicybasedexternalroutesResource, opts))
}

// Create takes the representation of a adminPolicyBasedExternalRoute and creates it.  Returns the server's representation of the adminPolicyBasedExternalRoute, and an error, if there is any.
func (c *FakeAdminPolicyBasedExternalRoutes) Create(ctx context.Context, adminPolicyBasedExternalRoute *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, opts v1.CreateOptions) (result *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(adminpolicybasedexternalroutesResource, adminPolicyBasedExternalRoute), &adminpolicybasedroutev1.AdminPolicyBasedExternalRoute{})
	if obj == nil {
		return nil, err
	}
	return obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRoute), err
}

// Update takes the representation of a adminPolicyBasedExternalRoute and updates it. Returns the server's representation of the adminPolicyBasedExternalRoute, and an error, if there is any.
func (c *FakeAdminPolicyBasedExternalRoutes) Update(ctx context.Context, adminPolicyBasedExternalRoute *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, opts v1.UpdateOptions) (result *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(adminpolicybasedexternalroutesResource, adminPolicyBasedExternalRoute), &adminpolicybasedroutev1.AdminPolicyBasedExternalRoute{})
	if obj == nil {
		return nil, err
	}
	return obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAdminPolicyBasedExternalRoutes) UpdateStatus(ctx context.Context, adminPolicyBasedExternalRoute *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, opts v1.UpdateOptions) (*adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(adminpolicybasedexternalroutesResource, "status", adminPolicyBasedExternalRoute), &adminpolicybasedroutev1.AdminPolicyBasedExternalRoute{})
	if obj == nil {
		return nil, err
	}
	return obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRoute), err
}

// Delete takes name of the adminPolicyBasedExternalRoute and deletes it. Returns an error if one occurs.
func (c *FakeAdminPolicyBasedExternalRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(adminpolicybasedexternalroutesResource, name), &adminpolicybasedroutev1.AdminPolicyBasedExternalRoute{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAdminPolicyBasedExternalRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(adminpolicybasedexternalroutesResource, listOpts)

	_, err := c.Fake.Invokes(action, &adminpolicybasedroutev1.AdminPolicyBasedExternalRouteList{})
	return err
}

// Patch applies the patch and returns the patched adminPolicyBasedExternalRoute.
func (c *FakeAdminPolicyBasedExternalRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *adminpolicybasedroutev1.AdminPolicyBasedExternalRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(adminpolicybasedexternalroutesResource, name, pt, data, subresources...), &adminpolicybasedroutev1.AdminPolicyBasedExternalRoute{})
	if obj == nil {
		return nil, err
	}
	return obj.(*adminpolicybasedroutev1.AdminPolicyBasedExternalRoute), err
}
