// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package sbdb

import "github.com/ovn-org/libovsdb/model"

const FDBTable = "FDB"

// FDB defines an object in FDB table
type FDB struct {
	UUID      string `ovsdb:"_uuid"`
	DpKey     int    `ovsdb:"dp_key"`
	MAC       string `ovsdb:"mac"`
	PortKey   int    `ovsdb:"port_key"`
	Timestamp int    `ovsdb:"timestamp"`
}

func (a *FDB) GetUUID() string {
	return a.UUID
}

func (a *FDB) GetDpKey() int {
	return a.DpKey
}

func (a *FDB) GetMAC() string {
	return a.MAC
}

func (a *FDB) GetPortKey() int {
	return a.PortKey
}

func (a *FDB) GetTimestamp() int {
	return a.Timestamp
}

func (a *FDB) DeepCopyInto(b *FDB) {
	*b = *a
}

func (a *FDB) DeepCopy() *FDB {
	b := new(FDB)
	a.DeepCopyInto(b)
	return b
}

func (a *FDB) CloneModelInto(b model.Model) {
	c := b.(*FDB)
	a.DeepCopyInto(c)
}

func (a *FDB) CloneModel() model.Model {
	return a.DeepCopy()
}

func (a *FDB) Equals(b *FDB) bool {
	return a.UUID == b.UUID &&
		a.DpKey == b.DpKey &&
		a.MAC == b.MAC &&
		a.PortKey == b.PortKey &&
		a.Timestamp == b.Timestamp
}

func (a *FDB) EqualsModel(b model.Model) bool {
	c := b.(*FDB)
	return a.Equals(c)
}

var _ model.CloneableModel = &FDB{}
var _ model.ComparableModel = &FDB{}
