// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PodListerExpansion is an autogenerated mock type for the PodListerExpansion type
type PodListerExpansion struct {
	mock.Mock
}

// NewPodListerExpansion creates a new instance of PodListerExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPodListerExpansion(t interface {
	mock.TestingT
	Cleanup(func())
}) *PodListerExpansion {
	mock := &PodListerExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
