// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PodNamespaceListerExpansion is an autogenerated mock type for the PodNamespaceListerExpansion type
type PodNamespaceListerExpansion struct {
	mock.Mock
}

// NewPodNamespaceListerExpansion creates a new instance of PodNamespaceListerExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPodNamespaceListerExpansion(t interface {
	mock.TestingT
	Cleanup(func())
}) *PodNamespaceListerExpansion {
	mock := &PodNamespaceListerExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
