// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PodNamespaceListerExpansion is an autogenerated mock type for the PodNamespaceListerExpansion type
type PodNamespaceListerExpansion struct {
	mock.Mock
}

type mockConstructorTestingTNewPodNamespaceListerExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewPodNamespaceListerExpansion creates a new instance of PodNamespaceListerExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPodNamespaceListerExpansion(t mockConstructorTestingTNewPodNamespaceListerExpansion) *PodNamespaceListerExpansion {
	mock := &PodNamespaceListerExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
