// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PodTemplateNamespaceListerExpansion is an autogenerated mock type for the PodTemplateNamespaceListerExpansion type
type PodTemplateNamespaceListerExpansion struct {
	mock.Mock
}

// NewPodTemplateNamespaceListerExpansion creates a new instance of PodTemplateNamespaceListerExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPodTemplateNamespaceListerExpansion(t interface {
	mock.TestingT
	Cleanup(func())
}) *PodTemplateNamespaceListerExpansion {
	mock := &PodTemplateNamespaceListerExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
