// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PodTemplateListerExpansion is an autogenerated mock type for the PodTemplateListerExpansion type
type PodTemplateListerExpansion struct {
	mock.Mock
}

type mockConstructorTestingTNewPodTemplateListerExpansion interface {
	mock.TestingT
	Cleanup(func())
}

// NewPodTemplateListerExpansion creates a new instance of PodTemplateListerExpansion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPodTemplateListerExpansion(t mockConstructorTestingTNewPodTemplateListerExpansion) *PodTemplateListerExpansion {
	mock := &PodTemplateListerExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
