/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/userdefinednetwork/v1"
)

// UserDefinedNetworkSpecApplyConfiguration represents an declarative configuration of the UserDefinedNetworkSpec type for use
// with apply.
type UserDefinedNetworkSpecApplyConfiguration struct {
	Topology       *v1.NetworkTopology      `json:"topology,omitempty"`
	Role           *v1.NetworkRole          `json:"role,omitempty"`
	MTU            *uint                    `json:"mtu,omitempty"`
	Subnets        []string                 `json:"subnets,omitempty"`
	ExcludeSubnets []string                 `json:"excludeSubnets,omitempty"`
	JoinSubnets    []string                 `json:"joinSubnets,omitempty"`
	IPAMLifecycle  *v1.NetworkIPAMLifecycle `json:"ipamLifecycle,omitempty"`
}

// UserDefinedNetworkSpecApplyConfiguration constructs an declarative configuration of the UserDefinedNetworkSpec type for use with
// apply.
func UserDefinedNetworkSpec() *UserDefinedNetworkSpecApplyConfiguration {
	return &UserDefinedNetworkSpecApplyConfiguration{}
}

// WithTopology sets the Topology field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Topology field is set to the value of the last call.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithTopology(value v1.NetworkTopology) *UserDefinedNetworkSpecApplyConfiguration {
	b.Topology = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithRole(value v1.NetworkRole) *UserDefinedNetworkSpecApplyConfiguration {
	b.Role = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithMTU(value uint) *UserDefinedNetworkSpecApplyConfiguration {
	b.MTU = &value
	return b
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithSubnets(values ...string) *UserDefinedNetworkSpecApplyConfiguration {
	for i := range values {
		b.Subnets = append(b.Subnets, values[i])
	}
	return b
}

// WithExcludeSubnets adds the given value to the ExcludeSubnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludeSubnets field.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithExcludeSubnets(values ...string) *UserDefinedNetworkSpecApplyConfiguration {
	for i := range values {
		b.ExcludeSubnets = append(b.ExcludeSubnets, values[i])
	}
	return b
}

// WithJoinSubnets adds the given value to the JoinSubnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the JoinSubnets field.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithJoinSubnets(values ...string) *UserDefinedNetworkSpecApplyConfiguration {
	for i := range values {
		b.JoinSubnets = append(b.JoinSubnets, values[i])
	}
	return b
}

// WithIPAMLifecycle sets the IPAMLifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAMLifecycle field is set to the value of the last call.
func (b *UserDefinedNetworkSpecApplyConfiguration) WithIPAMLifecycle(value v1.NetworkIPAMLifecycle) *UserDefinedNetworkSpecApplyConfiguration {
	b.IPAMLifecycle = &value
	return b
}
