// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OVNDisconnectedCallback is an autogenerated mock type for the OVNDisconnectedCallback type
type OVNDisconnectedCallback struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *OVNDisconnectedCallback) Execute() {
	_m.Called()
}
