/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/qos/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// QoSLister helps list QoSs.
// All objects returned here must be treated as read-only.
type QoSLister interface {
	// List lists all QoSs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.QoS, err error)
	// QoSs returns an object that can list and get QoSs.
	QoSs(namespace string) QoSNamespaceLister
	QoSListerExpansion
}

// qoSLister implements the QoSLister interface.
type qoSLister struct {
	indexer cache.Indexer
}

// NewQoSLister returns a new QoSLister.
func NewQoSLister(indexer cache.Indexer) QoSLister {
	return &qoSLister{indexer: indexer}
}

// List lists all QoSs in the indexer.
func (s *qoSLister) List(selector labels.Selector) (ret []*v1.QoS, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.QoS))
	})
	return ret, err
}

// QoSs returns an object that can list and get QoSs.
func (s *qoSLister) QoSs(namespace string) QoSNamespaceLister {
	return qoSNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// QoSNamespaceLister helps list and get QoSs.
// All objects returned here must be treated as read-only.
type QoSNamespaceLister interface {
	// List lists all QoSs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.QoS, err error)
	// Get retrieves the QoS from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.QoS, error)
	QoSNamespaceListerExpansion
}

// qoSNamespaceLister implements the QoSNamespaceLister
// interface.
type qoSNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all QoSs in the indexer for a given namespace.
func (s qoSNamespaceLister) List(selector labels.Selector) (ret []*v1.QoS, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.QoS))
	})
	return ret, err
}

// Get retrieves the QoS from the indexer for a given namespace and name.
func (s qoSNamespaceLister) Get(name string) (*v1.QoS, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("qos"), name)
	}
	return obj.(*v1.QoS), nil
}
