// Code generated by mockery v2.43.2. DO NOT EDIT.

package v1

import (
	mock "github.com/stretchr/testify/mock"
	labels "k8s.io/apimachinery/pkg/labels"

	v1 "github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"
)

// NetworkAttachmentDefinitionNamespaceLister is an autogenerated mock type for the NetworkAttachmentDefinitionNamespaceLister type
type NetworkAttachmentDefinitionNamespaceLister struct {
	mock.Mock
}

type NetworkAttachmentDefinitionNamespaceLister_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkAttachmentDefinitionNamespaceLister) EXPECT() *NetworkAttachmentDefinitionNamespaceLister_Expecter {
	return &NetworkAttachmentDefinitionNamespaceLister_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: name
func (_m *NetworkAttachmentDefinitionNamespaceLister) Get(name string) (*v1.NetworkAttachmentDefinition, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.NetworkAttachmentDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*v1.NetworkAttachmentDefinition, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *v1.NetworkAttachmentDefinition); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.NetworkAttachmentDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkAttachmentDefinitionNamespaceLister_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type NetworkAttachmentDefinitionNamespaceLister_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *NetworkAttachmentDefinitionNamespaceLister_Expecter) Get(name interface{}) *NetworkAttachmentDefinitionNamespaceLister_Get_Call {
	return &NetworkAttachmentDefinitionNamespaceLister_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *NetworkAttachmentDefinitionNamespaceLister_Get_Call) Run(run func(name string)) *NetworkAttachmentDefinitionNamespaceLister_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NetworkAttachmentDefinitionNamespaceLister_Get_Call) Return(_a0 *v1.NetworkAttachmentDefinition, _a1 error) *NetworkAttachmentDefinitionNamespaceLister_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkAttachmentDefinitionNamespaceLister_Get_Call) RunAndReturn(run func(string) (*v1.NetworkAttachmentDefinition, error)) *NetworkAttachmentDefinitionNamespaceLister_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: selector
func (_m *NetworkAttachmentDefinitionNamespaceLister) List(selector labels.Selector) ([]*v1.NetworkAttachmentDefinition, error) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*v1.NetworkAttachmentDefinition
	var r1 error
	if rf, ok := ret.Get(0).(func(labels.Selector) ([]*v1.NetworkAttachmentDefinition, error)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(labels.Selector) []*v1.NetworkAttachmentDefinition); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.NetworkAttachmentDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(labels.Selector) error); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkAttachmentDefinitionNamespaceLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NetworkAttachmentDefinitionNamespaceLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - selector labels.Selector
func (_e *NetworkAttachmentDefinitionNamespaceLister_Expecter) List(selector interface{}) *NetworkAttachmentDefinitionNamespaceLister_List_Call {
	return &NetworkAttachmentDefinitionNamespaceLister_List_Call{Call: _e.mock.On("List", selector)}
}

func (_c *NetworkAttachmentDefinitionNamespaceLister_List_Call) Run(run func(selector labels.Selector)) *NetworkAttachmentDefinitionNamespaceLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(labels.Selector))
	})
	return _c
}

func (_c *NetworkAttachmentDefinitionNamespaceLister_List_Call) Return(ret []*v1.NetworkAttachmentDefinition, err error) *NetworkAttachmentDefinitionNamespaceLister_List_Call {
	_c.Call.Return(ret, err)
	return _c
}

func (_c *NetworkAttachmentDefinitionNamespaceLister_List_Call) RunAndReturn(run func(labels.Selector) ([]*v1.NetworkAttachmentDefinition, error)) *NetworkAttachmentDefinitionNamespaceLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewNetworkAttachmentDefinitionNamespaceLister creates a new instance of NetworkAttachmentDefinitionNamespaceLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkAttachmentDefinitionNamespaceLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkAttachmentDefinitionNamespaceLister {
	mock := &NetworkAttachmentDefinitionNamespaceLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
