/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressservice/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EgressServiceSpecApplyConfiguration represents an declarative configuration of the EgressServiceSpec type for use
// with apply.
type EgressServiceSpecApplyConfiguration struct {
	SourceIPBy   *v1.SourceIPMode      `json:"sourceIPBy,omitempty"`
	NodeSelector *metav1.LabelSelector `json:"nodeSelector,omitempty"`
	Network      *string               `json:"network,omitempty"`
}

// EgressServiceSpecApplyConfiguration constructs an declarative configuration of the EgressServiceSpec type for use with
// apply.
func EgressServiceSpec() *EgressServiceSpecApplyConfiguration {
	return &EgressServiceSpecApplyConfiguration{}
}

// WithSourceIPBy sets the SourceIPBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceIPBy field is set to the value of the last call.
func (b *EgressServiceSpecApplyConfiguration) WithSourceIPBy(value v1.SourceIPMode) *EgressServiceSpecApplyConfiguration {
	b.SourceIPBy = &value
	return b
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *EgressServiceSpecApplyConfiguration) WithNodeSelector(value metav1.LabelSelector) *EgressServiceSpecApplyConfiguration {
	b.NodeSelector = &value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *EgressServiceSpecApplyConfiguration) WithNetwork(value string) *EgressServiceSpecApplyConfiguration {
	b.Network = &value
	return b
}
